services:
  certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./scripts/generate-certs.sh:/generate-certs.sh
    env_file:
      - .env
    command: >
      bash /generate-certs.sh